version: '3.8'
services: 
 init-server:
  build:
   context: init-server
   dockerfile: Dockerfile
  environment: 
    SA_PASSWORD: ${PASSWORD}
  links:
    - sql-server-instance
 sql-server-instance:
  build:
   context: sql-server-instance
   dockerfile: Dockerfile
  environment: 
    SA_PASSWORD: ${PASSWORD}
    ACCEPT_EULA : "Y"
  ports: 
   - 1433:1433
